import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-50">
          <Toaster   position="top-right"
        toastOptions={{
          style: {
            background: '#fff',
            color: '#374151',
            boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
            borderRadius: '0.375rem',
            padding: '0.75rem 1rem',
          },
        }} />
          {/* Rest of your existing code */}
        </div>
        {children}
      </body>
    </html>
  );
}
